auto: true
server_port: 4000
markdown: maruku
pagination: true
paginate: 2
permalink: pretty

#url: http://davefearon.com
url: http://localhost:4000

title: Jetpac Engineering Blog
author: Jetpac Engineering Team
description: 
keywords: jetpac, travel, engineering, eng, tech, html, html5, ios, cassandra, psotgres, data